apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sramota
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
- name: sramota
  newName: rg.fr-par.scw.cloud/djnd/sramota
  newTag: 'latest'
